apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: maxblog-deployment-{DEPLOYMENT}
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: maxblogapi
        role: {DEPLOYMENT}
    spec:
      imagePullSecrets:
      - name: awsecr-cred
      containers:
      - name: maxblogapi
        image: 175374130779.dkr.ecr.us-east-2.amazonaws.com/maxblog-repo:${IMAGE_TAG}
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000

