kind: Service
apiVersion: v1
metadata:
  name: maxblogapi-service
  labels:
    app: maxblogapi
    role: blue
    env: prod
spec:
  type: LoadBalancer
  selector:
    app: maxblogapi
    role: blue
  ports:
    - port: 80
      targetPort: 5000
